name: Generate Index

actions:
  permissions:
    contents: write
    pull-requests: write

# Job to generate index file
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          # Your script to generate index
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/teletcl/tele.git main
